remove inlined functions for faster compilation
rust-lang/llvm pull request #92
Opened 2017-09-17 20:19 UTC by andjo403

after inlining remove functions that is not called any more
reduces compile times due to the removed functions is not further optimized.

part of solution for https://github.com/rust-lang/rust/issues/44655

2017-09-17 22:11 UTC, alexcrichton commented
Wow those are some awesome wins you're seeing! Would you be willing to try to send this upstream to LLVM itself as well? Unfortunately I'm less familiar with their contribution process, but it'd be great to ensure that their experiences eyes also took a look at this!

2017-09-18 05:19 UTC, andjo403 commented
I'm waiting for a bugzilla account for LLVM so I can add a ticket upstream

2017-09-18 06:22 UTC, andjo403 commented
[llvm ticket](https://bugs.llvm.org/show_bug.cgi?id=34652)

2017-09-18 14:06 UTC, alexcrichton commented
Thanks @andjo403! Let's wait a few days and see what happens upstream there.

2017-09-18 16:03 UTC, dcci commented
LLVM dev here [with a hidden passion for rust] :)
I see the rationale behind your commit. I think it makes sense, and you're probably seeing a big benefit because you have a bunch of small functions (even better if marked as static) with a single caller.
If you look at the inliner code in LLVM you'll see it gives a ridicolous bonus (grep for `LastCallToStaticBonus`, or something along these lines).

I wonder whether it's better running GDCE after the inliner or having the inliner itself removing dead functions after they're inlined (admittedly, I haven't looked at whether the latter is feasible).

FWIW, what's your benchmark? Can you try with big cases (like, building rust, building clang itself, maybe with LTO [this last one generaly should leave a bunch of unused function around])

2017-09-18 16:08 UTC, alexcrichton commented
@dcci hello again! FWIW on https://github.com/rust-lang/rust/issues/44655 it mentions a 23% improvement for the racer project which I think is [relatively large](https://github.com/racer-rust/racer), and it also mentions a [15% improvement for rustc itself](https://github.com/rust-lang/rust/issues/44655#issuecomment-330053207) which I know for a fact is quite large! I haven't tried this out myself yet, though, to verify.

2017-09-18 16:08 UTC, dcci requested changes
See my comment.

2017-09-18 16:08 UTC, dcci commented on lib/Transforms/IPO/PassManagerBuilder.cpp
> +    // Removes functions that is not used due to inlining
nit: that "are" not used.

2017-09-18 16:12 UTC, dcci commented
OK, thanks for your datapoints.
FWIW, GDCE is `O(n)`, so I  don't expect that taking a lot of time, but still, we should make a more careful analysis before changing the standard `-O2` pipeline. If you're willing to run some tests on rust, I'm going to run something equivalent on C++ (as I mentioned earlier, I'm particularly interested in LTO).
I'm a little swamped at the moment so that my take a week or two before we get the patch in, how does that sound like as timeline?

Thanks!

2017-09-18 16:17 UTC, alexcrichton commented
Sure yeah! @andjo403 if you want to poke around as well I can try to reproduce the rustc build times and also test some projects like Cargo and some simple-ish LTO cases.

2017-09-18 16:54 UTC, andjo403 commented
@alexcrichton sounds good. will try some more projects was thinking of running the https://github.com/rust-lang-nursery/rustc-benchmarks compare.py but will have to install a virtualbox or something due to it is using make and I'm on windows.

2017-09-18 16:55 UTC, andjo403 commented on lib/Transforms/IPO/PassManagerBuilder.cpp
> +    // Removes functions that is not used due to inlining
thanks will fix this

2017-09-18 17:31 UTC, alexcrichton commented
Some stats:

These numbers are for whole compilations, basically how long it took `cargo build --release` to finish, which means it's timing a whole lot more than just LLVM:

* rustc itself 505s -> 423s
* cargo 215s -> 163s
* small async I/O server 57s -> 48s

Some other numbers

* Compiling Cargo with LTO, just the final rustc invocation 106s -> 95s


Definitely seems like some possible big improvements to be had! Apparently not helping LTO a whole lot though :(

2017-09-18 17:37 UTC, andjo403 commented
@dcci and @alexcrichton maybe I do not understand how LTO works but I do not see how functions can be removed from an other crate. the linkage must be not private for LTO to do something and it feels like GDCE only can remove private linkage functions.

2017-09-18 18:04 UTC, alexcrichton commented
@andjo403 oh I think it's just with LTO that typically LLVM works with much larger LLVM modules (lots more code in memory all at once). In theory there's also tons of inlining and in theory greater wins to be had, but the one test I had didn't look too promising unfortunately :(

2017-09-18 18:09 UTC, dcci commented
@alexcrichton Alex, I'm a little surprised of these numbers as, FWIW, LTO should be the kinda best case but not always really.
Please note that if you do LTO, the inliner runs twice. 1st time, during the per-TU pipeline (i.e. -O2 and -O3) and another time on the whole module.
I'm not sure how rust actually sets up the pipeline, but if it gets the stock from LLVM, you might consider adding the pass also to `populateLTOPassManager` (or something similar, I don't remember the name off the top of my head), otherwise, GDCE won't run after the inliner at link time.

2017-09-18 18:16 UTC, alexcrichton commented
Aha indeed! Looks like [there's a spot](https://github.com/andjo403/llvm-1/blob/42e941e24e38c8225bad59632ce56d13949c7f38/lib/Transforms/IPO/PassManagerBuilder.cpp#L735-L740) this PR as-is doesn't handle. I've updated that and will report back the LTO build for Cargo.

2017-09-18 18:27 UTC, dcci commented
Yes, that's exactly it. You were only getting the benefit from the per-TU pipeline.

2017-09-18 18:30 UTC, alexcrichton commented
Ah unfortunately that ended up having no impact at all :(

2017-09-18 18:32 UTC, andjo403 commented
@alexcrichton there is already one a some lines below https://github.com/andjo403/llvm-1/blob/42e941e24e38c8225bad59632ce56d13949c7f38/lib/Transforms/IPO/PassManagerBuilder.cpp#L747

2017-09-19 14:46 UTC, alexcrichton commented
Ah that'd explain the lack of improvements!

2017-09-21 18:51 UTC, dcci commented
@alexcrichton @andjo403 
So, I've been looking at this more closely. I'm not able to find any obvious regression, so I think I'm going for a slightly modified version of this patch for review (probably, we should also run another pass, GlobalOpt in tandem with GlobalDCE). Once that is done, I guess you guys can probably backport this thingy back? Of course, I'll give the correct attribution for the idea =)

2017-09-21 19:36 UTC, alexcrichton commented
@dcci sounds great, and thanks again for helping out with this! If you've got a patch I can run some tests for it for sure. And yeah we'll take care of backporting for our own "fork", no need to worry about that!

2017-09-21 19:48 UTC, andjo403 commented
shall I close this PR then?

2017-10-02 19:33 UTC, dcci commented
FWIW, I'm working on this, but the patch exposes a series of misoptimizations in LLVM that need to be fixed. I'm working on these now and I hope to enable the patch once they're all addressed.

2017-10-02 20:12 UTC, dcci commented
OK, I think the patch was placed in a slightly incorrect point in the pipeline.
Can you please re-run with the following patch applied?

Thanks!

```
diff --git a/lib/Transforms/IPO/PassManagerBuilder.cpp b/lib/Transforms/IPO/PassManagerBuilder.cpp
index b384629..9155d1a 100644
--- a/lib/Transforms/IPO/PassManagerBuilder.cpp
+++ b/lib/Transforms/IPO/PassManagerBuilder.cpp
@@ -499,10 +499,14 @@ void PassManagerBuilder::populateModulePassManager(
   // Start of CallGraph SCC passes.
   if (!DisableUnitAtATime)
     MPM.add(createPruneEHPass()); // Remove dead EH info
+  bool RunInliner = false;
   if (Inliner) {
     MPM.add(Inliner);
     Inliner = nullptr;
+    RunInliner = true;
   }
+
+
   if (!DisableUnitAtATime)
     MPM.add(createPostOrderFunctionAttrsLegacyPass());
   if (OptLevel > 2)
@@ -515,6 +519,18 @@ void PassManagerBuilder::populateModulePassManager(
   // pass manager that we are specifically trying to avoid. To prevent this
   // we must insert a no-op module pass to reset the pass manager.
   MPM.add(createBarrierNoopPass());
+
+  // The inliner performs some kind of dead code elimination as it goes,
+  // but there are cases that are not really caught by it. We might
+  // at some point consider teaching the inliner about them, but it
+  // is OK for now to run GlobalOpt + GlobalDCE in tandem as their
+  // benefits generally outweight the cost, making the whole pipeline
+  // faster. See PR34652.
+  if (RunInliner) {
+    MPM.add(createGlobalOptimizerPass());
+    MPM.add(createGlobalDCEPass());
+  }
+
   if (RunPartialInlining)
     MPM.add(createPartialInliningPass());
```

2017-10-02 20:53 UTC, andjo403 commented
have update this PR with the patch from @dcci so it shall be easier to test for others
I have started the compilation not sure if I will wait for the results tonight

2017-10-02 21:46 UTC, andjo403 commented
@dcci I have only tested to compile race once with standard rustc and once with the patch and I get 
LLVM Pass execution timing report for rust lib compilation 
standard rustc  Total Execution Time: 64.7500 seconds (68.0480 wall clock)
patch Total Execution Time: 35.9531 seconds (37.2969 wall clock)

and for all crates in racer the total time go from 405.71 secs to 315.5 secs
will run some more tests tomorrow

@alexcrichton can you also run some tests?

2017-10-02 22:14 UTC, dcci commented
OK, I think this is fine.

2017-10-05 18:27 UTC, dcci commented
Upstream rL314997 and rL314999.
Cheers.

2017-10-05 18:30 UTC, andjo403 commented
@dcci thanks for all the help 
working at the backport now for this repo

2017-10-05 18:31 UTC, andjo403 commented
haha to late :)

2017-10-05 18:32 UTC, alexcrichton commented
Thanks so much @dcci!

@andjo403 oh I actually just pushed this to the relevant branch, ensuring that it builds locally first though. @andjo403 want to send a PR to rust-lang/rust though?

2017-10-05 18:34 UTC, andjo403 commented
@alexcrichton yes I want to send a PR to rust-lang/rust

2017-10-05 18:34 UTC, closed without merging

2017-10-05 18:38 UTC, cuviper commented
@alexcrichton looks like you only pushed 314997 -- did you intend to backport 314999 too?

2017-10-05 18:45 UTC, alexcrichton commented
Oh oops, thanks @cuviper! Apparently when I fetched 314999 wasn't in the mirror yet...

2017-10-05 19:17 UTC, andjo403 commented
@alexcrichton I wanted to test the the commit https://github.com/rust-lang/rust/commit/8fd3c8f769065aa102d97ddc253d7a6df2b53d7b
 before making a PR but I get:

> failed to run: /home/ubuntu/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/ubuntu/rust/src/bootstrap/Cargo.toml

2017-10-05 19:19 UTC, alexcrichton commented
@andjo403 sounds suspicious! Mind gisting the full error you saw?

2017-10-05 19:21 UTC, andjo403 commented
https://gist.github.com/andjo403/fd4aa056592f7ce807cc49f6ff2067c8

2017-10-05 19:23 UTC, alexcrichton commented
Ah try doing `git submodule update --init --recursive` maybe?

2017-10-05 19:25 UTC, andjo403 commented
yes solved it thanks